export const SELECT_TECHNOLOGY = "app/Quizz/SELECT_TECHNOLOGY";
export const SELECT_TECHNOLOGY_SUCCESS = "app/Quizz/SELECT_TECHNOLOGY_SUCCESS";
export const SELECT_TECHNOLOGY_FAILURE = "app/Quizz/SELECT_TECHNOLOGY_FAILURE";

export const SUBMIT_QUIZZ = "app/Quizz/SUBMIT_QUIZZ";
export const SUBMIT_QUIZZ_SUCCESS = "app/Quizz/SUBMIT_QUIZZ_SUCCESS";
export const SUBMIT_QUIZZ_FAILURE = "app/Quizz/SUBMIT_QUIZZ_FAILURE";
